name: Dev Deploy

on:
  workflow_dispatch:

jobs:
  build:
    environment: Dev
    runs-on: ubuntu-latest
    build-ubuntu:
      name: Calling Reusable workflow
      uses: RGupta0323/ReusableWorkflows/.github/workflows/DevDeploy.yml@master
      with:
        runs-on: ubuntu-latest
    steps:
      - name: Test Step
        run: actions/checkout@v2


