name: Dev Deploy

on:
  workflow_dispatch:

jobs:
  build:
    environment: Dev
    runs-on: ubuntu-latest
    steps:
      - uses: RGupta0323/ReusableWorkflows/.github/workflows/DevDeploy.yml@master


