name: Dev Deploy

on:
  workflow_dispatch:

jobs:
  build:
    environment: Dev
    runs-on: ubuntu-latest
    uses: RGupta0323/ReusableWorkflows/.github/workflows/DevDeploy.yml@master
    
    steps:
      - name: Test Step
        run: actions/checkout@v2


