name: Dev Deploy

on:
  workflow_dispatch:

jobs:
  build:
    uses: RGupta0323/ReusableWorkflows/.github/workflows@main
    environment: Dev
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v2


