name: Cdk Template Dev

on:
  push:
    branches:
      - master
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    environment: sandbox
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install python dependencies
        run: pip install -r requirements-dev.txt
