name: Dev Deploy

on:
  workflow_dispatch:

jobs:
  build:
    uses: RGupta0323/ReusableWorkflows/.github/workflows/action.yml@main
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-east-1


  do-it:
    environment: Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2


