name: Cdk Template Dev

on:
  push:
    branches:
      - master
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    environment: sandbox
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Install python dev dependencies
        run: pip install -r requirements-dev.txt

      - name: Install python infrastructure dependencies
        run: pip install -r requirements-infra.txt

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '16.3.0'

      - name: install awsk cdk
        run: npm install -g aws-cdk

      - name: Configure AWS Credentials (Raw ACcount)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}

      - name: cdk synth
        run: cdk synth fitness-app-dev-stack

      - name: cdk deploy
        run: cdk deploy fitness-app-dev-stack --require-approval never
