name: Dev Deploy

on:
  workflow_dispatch:


permissions:
  id-token: write
  contents: read

jobs:
  checkout-repo:
    environment: Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '16.3.0'

      - name: install aws cdk
        run: npm install -g aws-cdk

      - name: Configure AWS Credentials (Raw ACcount)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.aws-access-key-id }}
          aws-secret-access-key: ${{ env.aws-secret-access-key }}
          aws-region: ${{ env.aws-region }}

